training_set = [
{"title":"Me (24) and GF (24) - She has issues with affection/attraction", "poster":{"age":"24", "gender":""}, "other":{"age":"24", "gender":"", "relationship":"GF"}},
{"title":"My [24F] gf found out she was pregnant and wants have an abortion but I refuse her to do it", "poster":{"age":"", "gender":"M"}, "other":{"age":"24", "gender":"F", "relationship":"girlfriend"}},
{"title":"How to ask my roommate [26] to stop spending so much time with my [29] dog?", "poster":{"age":"29", "gender":""}, "other":{"age":"26", "gender":"", "relationship":"roommate"}},
{"title":"My 23f husband 28f was searching m4m. Today I found out he was hooking up with a bunch of guys before we dated.", "poster":{"age":"23", "gender":"F"}, "other":{"age":"28", "gender":"F", "relationship":"Husband"}},
{"title":"My mom (46F) allowed her brother (50sM), niece (20F), and niece's husband (20M) to move in with us, and now it is causing me (22M) to resent my mom. Advice?", "poster":{"age":"", "gender":""}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"I [20 M] am nervous about my girlfriend [21 F] of 5 months buying drugs and hanging out with the dealer. Feeling uncomfortable with her past.", "poster":{"age":"20", "gender":"M"}, "other":{"age":"21", "gender":"F", "relationship":"girlfriend"}},
{"title":"I (24F) am having a hard time initiating sex with my BF (25M) of 1.5 years", "poster":{"age":"24", "gender":"F"}, "other":{"age":"25", "gender":"M", "relationship":"BF"}},
{"title":"What are some tips so that I [32 M] can help handle my girlfriend of 2 years [32 F] finances, while avoiding coming across as a controlling jerk", "poster":{"age":"32", "gender":"M"}, "other":{"age":"32", "gender":"F", "relationship":"girlfriend"}},
{"title":"My (41f) partner (41m) constantly blames me for everything and my life has become a nightmare", "poster":{"age":"41", "gender":"F"}, "other":{"age":"41", "gender":"M", "relationship":"partner"}},
{"title":"I [18 M] have been dating my gf [18 F] for a month, and I want to build our personal relationship more, rather than our physical relationship", "poster":{"age":"18", "gender":"M"}, "other":{"age":"18", "gender":"F", "relationship":"gf"}},
{"title":"Me (24) with GF (25) - How to deal with lack of attraction", "poster":{"age":"24", "gender":""}, "other":{"age":"25", "gender":"", "relationship":"gf"}},
{"title":"I (25M) inherently want unhealthy relationship, any way to channel this into something positive?", "poster":{"age":"25", "gender":"M"}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"[20/F] with [29/M], cares more about his friend [29/F] and her breakup than me grieving over the loss of a loved one.", "poster":{"age":"20", "gender":"F"}, "other":{"age":"29", "gender":"M", "relationship":""}},
{"title":"I [17M] have no idea how to have a conversation with someone unless its a group convo", "poster":{"age":"17", "gender":"M"}, "other":{"age":"17", "gender":"M", "relationship":""}},
{"title":"I (30F) am pretty sure I freaked out this guy (30M) I've been dating for 3 months with a fantasy I spoke of", "poster":{"age":"30", "gender":"F"}, "other":{"age":"30", "gender":"M", "relationship":"guy"}}
]

test_set = [
{"title":"Worried that my (25F) insecurities are affecting my relationship with my boyfriend (30M)", "poster":{"age":"25", "gender":"F"}, "other":{"age":"30", "gender":"M", "relationship":"boyfriend"}},
{"title":"Me [33/F] with my [54/M] 2 months. Help, I could rip my heart out if it were possible.", "poster":{"age":"33", "gender":"F"}, "other":{"age":"54", "gender":"M", "relationship":""}},
{"title":"A big sticky issue between us (28F + M)", "poster":{"age":"", "gender":""}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"I [25M] inherently want unhealthy relationship, any way to channel this into something positive?", "poster":{"age":"25", "gender":"M"}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"My [24/F] boyfriend [28/M] of 5 months isn't vocal enough.", "poster":{"age":"24", "gender":"F"}, "other":{"age":"28", "gender":"M", "relationship":"boyfriend"}},
{"title":"Me [34 M/F] with the mother of my child [34F] and girlfriend of 7 years. Is it time to call it quits?", "poster":{"age":"34", "gender":"M"}, "other":{"age":"34", "gender":"F", "relationship":"girlfriend"}},
{"title":"I (48M) was on the phone with my dad (72) today and he accidentally didn't hang up, and I heard him say something that has me more upset than I've ever been in my life.", "poster":{"age":"48", "gender":"M"}, "other":{"age":"72", "gender":"M", "relationship":"dad"}},
{"title":"My [23M] girlfriend of 6 months [23F] is worried that we will gradually become 'just friends'", "poster":{"age":"23", "gender":"M"}, "other":{"age":"23", "gender":"F", "relationship":"girlfriend"}},
{"title":"A big sticky issue between us (28F + M)", "poster":{"age":"", "gender":""}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"Me [33/F] with my [54/M] 2 months. Help, I could rip my heart out if it were possible.", "poster":{"age":"33", "gender":"F"}, "other":{"age":"54", "gender":"M", "relationship":""}},
{"title":"Boyfriend refuses to give me head", "poster":{"age":"", "gender":""}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"My pregnant wife [29F] doesn't acknowledge my [29M] presence after the birth of our baby and seems to think she will have to do all the work.", "poster":{"age":"29", "gender":"M"}, "other":{"age":"29", "gender":"F", "relationship":"wife"}},
{"title":"Me [23F] with my Girlfriend [21F] 4months are in disagreement on living partly together.", "poster":{"age":"23", "gender":"F"}, "other":{"age":"21", "gender":"F", "relationship":"gf"}},
{"title":"I [17M] have no idea how to have a conversation with anyone unless its in a group", "poster":{"age":"17", "gender":"M"}, "other":{"age":"", "gender":"", "relationship":""}},
{"title":"I (22F) am feeling so confused about my relationship with my SO (21M)", "poster":{"age":"22", "gender":"F"}, "other":{"age":"21", "gender":"M", "relationship":"so"}},
{"title":"UPDATE: Me [29F] with my husband [39M] married 4.5 yrs, 2 small children. He is cheating on me with other men.", "poster":{"age":"29", "gender":"F"}, "other":{"age":"39", "gender":"M", "relationship":"husband"}},
{"title":"Boyfriend [21M] refuses to give me [19F] head", "poster":{"age":"19", "gender":"F"}, "other":{"age":"21", "gender":"M", "relationship":"boyfriend"}},
{"title":"Informed that my son [16M] has been severely bullying kids at his high school, unsure of what to do", "poster":{"age":"", "gender":""}, "other":{"age":"16", "gender":"M", "relationship":"son"}},
{"title":"Me [48 F] with my [60 M] 6 year relationship ending", "poster":{"age":"48", "gender":"F"}, "other":{"age":"60", "gender":"M", "relationship":""}},
{"title":"Me [26 M] with my love interest [26F] of a month and some change. I bought her a gift I saw on her Twitter feed 6 months ago, would this push her away?", "poster":{"age":"26", "gender":"M"}, "other":{"age":"26", "gender":"F", "relationship":"love interest"}},
{"title":"Every time my fiance (27M) of 4.5 years is upset, he becomes really cold and critical towards me (26F). Should I move out with him?", "poster":{"age":"26", "gender":"F"}, "other":{"age":"27", "gender":"M", "relationship":"fiance"}},
{"title":"I [18 M] have a bad crush on my friend [18 F] since 1 year", "poster":{"age":"18", "gender":"M"}, "other":{"age":"18", "gender":"F", "relationship":"friend"}},
{"title":"Me [20M] and my girlfriend [22F] have been together for two months, I want to break up but feel way too guilty", "poster":{"age":"20", "gender":"M"}, "other":{"age":"22", "gender":"F", "relationship":"girlfriend"}},
{"title":"How to ask my roommate [26] to stop spending so much time with my [29] dog?", "poster":{"age":"29", "gender":""}, "other":{"age":"26", "gender":"", "relationship":"roommate"}},
{"title":"My [34 F] mom [60 F] hates my haircut and keeps putting me down. Help.", "poster":{"age":"34", "gender":"F"}, "other":{"age":"60", "gender":"F", "relationship":"mom"}},
{"title":"What does he (22m) mean when he says this to me (21f)", "poster":{"age":"21", "gender":"F"}, "other":{"age":"22", "gender":"M", "relationship":""}}
]
